name: terragrunt-apply-prd

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: prd
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      TG_ROOT: ${{ vars.TG_ROOT }}
      TERRAGRUNT_NON_INTERACTIVE: "true"
      TF_INPUT: "false"

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: Install Terragrunt
        run: |
          TG_VER="0.58.12"
          curl -sSL -o terragrunt "https://github.com/gruntwork-io/terragrunt/releases/download/v${TG_VER}/terragrunt_linux_amd64"
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/terragrunt

      - name: Configure AWS (OIDC) - PRD
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_PRD }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terragrunt run-all apply (PRD)
        run: |
          cd "$TG_ROOT/prd"
          terragrunt run-all apply --terragrunt-non-interactive -auto-approve
